version: "3.0"
services:
  memos:
    image: neosmemo/memos:latest
    container_name: memos
    volumes:
      - ./.memos/:/var/opt/memos
    ports:
      - 8004:5230
  microbin:
    image: danielszabo99/microbin:latest
    container_name: microbin
    ports:
      - 8005:8080
